#-------------------------------------------------
#                Wardrobe Config                 -
#-------------------------------------------------

Wardrobe_Work:
  GUI_Tile:
    # 2 Page must have a 2 different name
    Page_1: "Wardrobe (1/2)"
    Page_2: "Wardrobe (2/2)"
  Rank_Slots:
    # Wardrobe admin permission
    Admin: group.admin
    # Rank to have slots
    Slots_2: gourp.default
    Slots_5: group.vip
    Slots_9: group.vip+
    Slots_13: group.mvp
    Slots_18: group.mvp+
  # This feature is a specific check for item by using lore check
  Helmet_Lore_Check: "HELMET"
  # If lore of item contain this, it will allow you to put that armor in to Wardrobe.
#--------------Custom------------------
  Close_Button:
    Name: "&cClose"
    # you can add lore like this
    # lore:
    # - "<Lore1>"
    # - "<Lore2>"
    Lore:
  Next_Page_Button:
    Name: "&aNext Page"
    Lore:
      - "&ePage 2"
  Previous_Page_Button:
    Name: "&aPrevious Page"
    Lore:
      - "&ePage 1"
  # Available Slots
  Available_Slot:
    # %slot% is a placeholder to show slot number
    Helmet:
      Name: "&aSlot %slot% Helmet"
      Lore:
        - "&7Place a helmet here to add it"
        - "&7to the armor set."
    Chestplate:
      Name: "&aSlot %slot% Chestplate"
      Lore:
        - "&7Place a chestplate here to add it"
        - "&7to the armor set."
    Leggings:
      Name: "&aSlot %slot% Leggings"
      Lore:
        - "&7Place a pair of Leggings here"
        - "&7to add it to the armor set."
    Boots:
      Name: "&aSlot %slot% Boots"
      Lore:
        - "&7Place a pair of boots here to"
        - "&7add it to the armor set."
    Empty_Button:
      Name: "&7Slot %slot% &cEmpty"
      Lore:
        - "&7This wardrobe slot contains no"
        - "&7armor."
    Ready_Button:
      Name: "&7Slot %slot%: &aReady"
      Lore:
        - "&7This wardrobe slot is ready to"
        - "&7be equipped."
        - " "
        - "&eClick to euip this armor set!"
    Equipped_Button:
      Name: "&7Slot %slot%: &aEquipped"
      Lore:
        - "&7This wardrobe slot contains your"
        - "&7current armor set."
        - " "
        - "&eClick to unequip this armor set!"
  # Lore of locked slot
  Locked_Slot:
    Name: "&7Slot %slot% &cLocked"
    Lore: 
      - "&7This wardrobe slot is"
      - "&7locked and cannot be used"
      - " "
    Rank_Requires_Prefix:
      Slots_2: "&cRequires &7DEFAULT"
      Slots_5: "&cRequires &aVIP"
      Slots_9: "&cRequires &aVIP&6+"
      Slots_13: "&cRequires &bMVP"
      Slots_18: "&cRequires &bMVP&c+"
  Go_Back:
    # You can make player or console execute command like this
    # Console: command (with no "/")
    # Player: command (with no "/")
    Enable: true
    Command: sbmenu
    Name: "&aGo Back"
    Lore: 
      - "&7To SkyBlock Menu"
    
    
Wardrobe_Message:
  # Please just use normal message 
  Permission_Denied: '&fUnknown command. Type "/help" for help.'
  No_Space: "&cYou don't have enough space in your inventory!"
  Modify_Armor_Denied: "&cYou can not modify your equipped armor set!"
